"""
Generate a synthetic OCR eval corpus for Phase 03.

Produces ~15 Vietnamese "VinFast-style" purchase contracts as **text-selectable PDFs**
(text layer intact, so OCR providers must extract from a real PDF, not just an image),
paired with a ground-truth JSONL that downstream Track-1 extraction configs can be
scored against.

All names, addresses, IDs, numbers are procedurally generated by `Faker` and prefixed
with a clear "SYNTH-" marker so a human reader cannot mistake them for real data.

Output layout
-------------
    data/Scan/synth_phase03/contract_<slug>.pdf          (15 PDFs)
    data/processed/phase03_synth_contracts.jsonl          (15 GT records, paired by case_id)
    data/Scan/synth_phase03/manifest.json                 (run-level metadata)

The GT JSONL mirrors the layout of the (future) EvalLog schema: case_id, source_pdf,
ground_truth_fields (dict).  Track-1 configs (Phase 04) will score against this.

Usage
-----
    conda activate vsf
    python scripts/phase-03/generate_synthetic_contracts.py --n 15

Notes
-----
* Phase 03 is currently `not started` in doc/phases/INDEX.md — this script is the
  seed asset, not an experiment.  The first OCR bake-off run will live in a
  separate `run_ocr_*.py`.
* PDFs use DejaVuSans (registered from this script's `fonts/` folder) so
  Vietnamese diacritics render correctly. The fonts are bundled with
  matplotlib (Bitstream-Vera + font-exception license) and copied into the
  repo so the generator is self-contained and offline-deterministic.
* Data is 100% synthetic. No real VinFast customer, dealer, or bank data is
  reused. Every identifier carries a SYNTH- prefix or a @example.test domain.
"""
from __future__ import annotations

import argparse
import json
import random
import string
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path

from faker import Faker

# reportlab — pure-Python PDF renderer, already used in similar OP5 stack.
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# --- Logo asset ----------------------------------------------------------
# The 'V' emblem was extracted from the public VinFast contract template at
# data/scan/vf_pc01.81.1_mau-hd-mua-ban-xe-o-to-dien-vf_pc.pdf page 1 and is
# bundled with this script under assets/ with a SYNTH watermark + red bar to
# make it unmistakable that the asset is for OCR testing only, not a real
# VinFast brand asset.
LOGO_PATH = Path(__file__).resolve().parent / "assets" / "vinfast_logo_synth.png"

REPO_ROOT = Path(__file__).resolve().parents[2]
SCAN_OUT = REPO_ROOT / "data" / "Scan" / "synth_phase03"
PROCESSED_OUT = REPO_ROOT / "data" / "processed"
PROCESSED_OUT.mkdir(parents=True, exist_ok=True)
SCAN_OUT.mkdir(parents=True, exist_ok=True)

GT_OUT = PROCESSED_OUT / "phase03_synth_contracts.jsonl"
MANIFEST_OUT = SCAN_OUT / "manifest.json"


# ---------------------------------------------------------------------------
# Synth field generation
# ---------------------------------------------------------------------------

# VinFast model names are public; used here only as template strings. The
# randomized per-record fields (version, color, price, etc.) are the only
# variation, and they all carry the SYNTH marker downstream.
VF_MODELS = [
    ("VF 3", ["Plus", "Eco"]),
    ("VF 5", ["Plus", "Eco"]),
    ("VF 6", ["Plus", "Eco"]),
    ("VF 7", ["Plus", "Eco"]),
    ("VF 8", ["Plus", "Eco", "Lux"]),
    ("VF 9", ["Plus", "Eco", "Lux"]),
]

# Real-looking but obviously fake bank names (all carry SYNTH- marker).
FAKE_BANKS = [
    "SYNTH Ngân hàng TMCP Á Đông Dương",
    "SYNTH Ngân hàng TMCP Phương Đông Việt",
    "SYNTH Ngân hàng TMCP Đại Việt",
    "SYNTH Ngân hàng TMCP Tổng Hợp Sài Gòn",
    "SYNTH Ngân hàng TMCP Bắc Trung Nam",
]

VEHICLE_COLORS = [
    "Trắng", "Đen", "Bạc", "Xám", "Đỏ", "Xanh dương", "Xanh lá",
]


@dataclass
class SynthContract:
    case_id: str
    source_pdf: str
    contract_no: str
    sign_date: str
    seller_name: str
    seller_address: str
    seller_tax_id: str
    seller_rep: str
    seller_rep_title: str
    seller_bank: str
    seller_account: str
    seller_account_holder: str
    buyer_name: str
    buyer_address: str
    buyer_phone: str
    buyer_email: str
    buyer_id: str
    model: str
    version: str
    color: str
    vin: str
    includes_battery: bool
    unit_price_vnd: int
    total_price_words_vi: str
    payment_stage_1_vnd: int
    payment_method: str  # "trả thẳng" | "trả góp"
    own_capital_vnd: int | None
    credit_notice_vnd: int | None
    delivery_date: str
    delivery_place: str
    special_offer_a: str = ""
    special_offer_b: str = ""
    special_offer_c: str = ""
    special_offer_d: str = ""
    page2_notes: list[str] = field(default_factory=list)


def _rand_digits(n: int, rng: random.Random) -> str:
    return "".join(rng.choice(string.digits) for _ in range(n))


def _rand_upper(n: int, rng: random.Random) -> str:
    return "".join(rng.choice(string.ascii_uppercase) for _ in range(n))


def _vi_amount_words(amount_vnd: int) -> str:
    """Money-in-words for GT field. OCR text layer uses digit form, so this
    string is only used to populate `ground_truth_fields.total_price_words_vi`.
    """
    return f"{amount_vnd:,} đồng (SYNTH — số tiền bằng chữ tự sinh)"


def _generate_one(idx: int, seed: int) -> SynthContract:
    rng = random.Random(seed)
    faker = Faker("vi_VN")
    Faker.seed(seed)

    model, versions = rng.choice(VF_MODELS)
    version = rng.choice(versions)
    color = rng.choice(VEHICLE_COLORS)

    # VIN follows a realistic 17-char pattern but always prefixed SYNTH.
    vin = "SYNTH" + _rand_upper(2, rng) + _rand_digits(10, rng)
    includes_battery = rng.random() < 0.55  # ~55% of deals include the battery

    # Realistic-ish VND price band per model.
    base_price = {
        "VF 3": (340_000_000, 420_000_000),
        "VF 5": (520_000_000, 620_000_000),
        "VF 6": (680_000_000, 780_000_000),
        "VF 7": (880_000_000, 1_000_000_000),
        "VF 8": (1_050_000_000, 1_300_000_000),
        "VF 9": (1_500_000_000, 1_900_000_000),
    }[model]
    # Round to nearest 10M VND for clean OCR reads.
    unit_price = rng.randrange(base_price[0], base_price[1], 10_000_000)
    stage1 = round(unit_price * rng.uniform(0.10, 0.30), -6)
    stage1 = max(stage1, 50_000_000)

    payment_method = "trả góp" if rng.random() < 0.45 else "trả thẳng"
    own_capital = None
    credit_notice = None
    if payment_method == "trả góp":
        own_capital = round(unit_price * rng.uniform(0.20, 0.40), -6)
        credit_notice = unit_price - own_capital

    sign_date = faker.date_between(start_date="-90d", end_date="today").isoformat()
    delivery_date = (
        faker.date_between(start_date="today", end_date="+60d").isoformat()
    )

    return SynthContract(
        case_id=f"synth-ctr-{idx:03d}",
        source_pdf=f"contract_synth-ctr-{idx:03d}.pdf",
        contract_no=f"SYNTH-CTR-{idx:03d}/{seed % 9999:04d}",
        sign_date=sign_date,
        seller_name="Công ty TNHH Kinh doanh Ô tô Điện SYNTH Việt Nam",
        seller_address=faker.address().replace("\n", ", "),
        seller_tax_id=f"SYNTH{_rand_digits(10, rng)}",
        seller_rep=faker.name(),
        seller_rep_title=rng.choice(
            ["Giám đốc", "Phó Giám đốc", "Trưởng phòng Kinh doanh"]
        ),
        seller_bank=rng.choice(FAKE_BANKS),
        seller_account=_rand_digits(12, rng),
        seller_account_holder="Công ty TNHH Kinh doanh Ô tô Điện SYNTH Việt Nam",
        buyer_name=f"SYNTH-{faker.name()}",
        buyer_address=faker.address().replace("\n", ", "),
        buyer_phone=f"+84-SYNTH-{_rand_digits(9, rng)}",
        buyer_email=f"buyer.{idx:03d}@example.test",
        buyer_id=f"SYNTH{_rand_digits(9, rng)}",
        model=model,
        version=version,
        color=color,
        vin=vin,
        includes_battery=includes_battery,
        unit_price_vnd=unit_price,
        total_price_words_vi=_vi_amount_words(unit_price),
        payment_stage_1_vnd=int(stage1),
        payment_method=payment_method,
        own_capital_vnd=int(own_capital) if own_capital else None,
        credit_notice_vnd=int(credit_notice) if credit_notice else None,
        delivery_date=delivery_date,
        delivery_place=faker.city(),
        special_offer_a="Ưu đãi giảm 2% theo CTKM SYNTH-AUTUMN-2026",
        special_offer_b="Tặng 5.000.000 VNĐ phụ kiện chính hãng",
        special_offer_c="CBNV cấp bậc Senior — giảm thêm 1,5%",
        special_offer_d="Vinclub hạng Gold — tích điểm 1,2x",
        page2_notes=[
            "Khách Hàng cần duy trì eSIM để sử dụng các tính năng thông minh.",
            "Bên Bán sẽ xử lý dữ liệu cá nhân theo Chính sách Bảo vệ Dữ liệu Cá nhân SYNTH.",
        ],
    )


# ---------------------------------------------------------------------------
# PDF rendering
# ---------------------------------------------------------------------------

# --- Vietnamese-capable TTF registration ---------------------------------
# reportlab's built-in Helvetica is WinAnsi-encoded and mangles Vietnamese
# diacritics to ■ glyphs. Register DejaVuSans (shipped with matplotlib, full
# Vietnamese coverage, license: Bitstream-Vera + font-exception) from this
# script's local fonts/ folder so the generator is self-contained.
_FONT_DIR = Path(__file__).resolve().parent / "fonts"
_FONT_REG = "DejaVuSans"
_FONT_BOLD = "DejaVuSans-Bold"
_TTF_REG = _FONT_DIR / "DejaVuSans.ttf"
_TTF_BOLD = _FONT_DIR / "DejaVuSans-Bold.ttf"
if not _TTF_REG.exists() or not _TTF_BOLD.exists():
    raise RuntimeError(
        f"Required TTF missing under {_FONT_DIR}. "
        "Expected DejaVuSans.ttf and DejaVuSans-Bold.ttf."
    )
pdfmetrics.registerFont(TTFont(_FONT_REG, str(_TTF_REG)))
pdfmetrics.registerFont(TTFont(_FONT_BOLD, str(_TTF_BOLD)))
# Register the family so <b>...</b> tags in Paragraph resolve correctly.
registerFontFamily(_FONT_REG, normal=_FONT_REG, bold=_FONT_BOLD,
                   italic=_FONT_REG, boldItalic=_FONT_BOLD)


def _build_styles():
    styles = getSampleStyleSheet()
    base = ParagraphStyle(
        "VnBase",
        parent=styles["Normal"],
        fontName=_FONT_REG,
        fontSize=11,
        leading=14,
    )
    # Big page title, in hoa, đậm, có viền dưới — matches the original template.
    title = ParagraphStyle(
        "VnTitle",
        parent=styles["Heading1"],
        fontName=_FONT_BOLD,
        fontSize=17,
        leading=22,
        alignment=1,  # center
        spaceAfter=6,
        borderPadding=4,
        borderWidth=0,  # drawn manually below via table border (see _title_block)
    )
    h2 = ParagraphStyle(
        "VnH2",
        parent=styles["Heading2"],
        fontName=_FONT_BOLD,
        fontSize=12,
        leading=15,
        spaceBefore=6,
        spaceAfter=2,
    )
    section_label = ParagraphStyle(
        "VnLabel",
        parent=base,
        fontName=_FONT_BOLD,
        fontSize=11,
        leading=14,
        spaceBefore=4,
        spaceAfter=0,
    )
    footer = ParagraphStyle(
        "VnFooter",
        parent=base,
        fontSize=9,
        leading=11,
        alignment=1,  # center
    )
    return base, title, h2, section_label, footer


def _kv_table(rows, base_style):
    data = [
        [Paragraph(f"<b>{k}</b>", base_style), Paragraph(v or "—", base_style)]
        for k, v in rows
    ]
    t = Table(data, colWidths=[5.5 * cm, 11 * cm])
    t.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ]
        )
    )
    return t


def _vehicle_table(c: SynthContract, base_style):
    battery_text = "gồm pin" if c.includes_battery else "không gồm pin"
    desc = (
        f"Xe {c.model} [{battery_text}]<br/>"
        f"Phiên bản: {c.version} - Màu: {c.color} - Số khung: {c.vin}<br/>"
        "Xe mới 100%, theo tiêu chuẩn của Nhà sản xuất."
    )
    rows = [
        ["TT", "Mô tả xe", "Số lượng", "Đơn Giá (VNĐ)", "Thành tiền (VNĐ)"],
        ["1", Paragraph(desc, base_style), "1", f"{c.unit_price_vnd:,}", f"{c.unit_price_vnd:,}"],
    ]
    t = Table(rows, colWidths=[1 * cm, 8 * cm, 1.5 * cm, 3.5 * cm, 3.5 * cm])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#d9d9d9")),
                ("FONTNAME", (0, 0), (-1, 0), _FONT_BOLD),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return t


def _header_band(c: SynthContract, base_style) -> Table:
    """Top of page: logo (left) + contract_no/date (right). Matches original."""
    logo = Image(str(LOGO_PATH), width=3 * cm, height=2.5 * cm)
    right_block = Table(
        [
            [Paragraph(f"<b>Số: {c.contract_no}</b>", base_style)],
            [Paragraph(f"có hiệu lực ngày {c.sign_date}", base_style)],
        ],
        colWidths=[6 * cm],
        hAlign="RIGHT",
    )
    right_block.setStyle(
        TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")])
    )
    band = Table(
        [[logo, right_block]],
        colWidths=[10 * cm, 7 * cm],
    )
    band.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return band


def _title_block(c: SynthContract, title_style) -> Table:
    """Big centered title with a thick black underline (matches original)."""
    t = Table(
        [[Paragraph("HỢP ĐỒNG MUA BÁN XE Ô TÔ ĐIỆN VINFAST", title_style)]],
        colWidths=[19 * cm],
    )
    t.setStyle(
        TableStyle(
            [
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("LINEBELOW", (0, 0), (-1, -1), 1.2, colors.black),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return t


def _party_block(c: SynthContract, base_style, label_style) -> list:
    """Inline-label party block, no table — matches the original template.

    Each line is one Paragraph like:
        <b>Địa chỉ:</b> 9 Jane Số, ...
    """
    seller_lines = [
        ("BÊN BÁN:", c.seller_name),
        ("Địa chỉ:", c.seller_address),
        ("MSDN:", c.seller_tax_id),
        ("Đại diện:", f"{c.seller_rep} - Chức vụ: {c.seller_rep_title}"),
        ("Tài khoản:", f"{c.seller_account} tại {c.seller_bank}"),
        ("Chủ tài khoản:", c.seller_account_holder),
    ]
    buyer_lines = [
        ("KHÁCH HÀNG:", c.buyer_name),
        ("Địa chỉ:", c.buyer_address),
        ("Điện thoại:", f"{c.buyer_phone} - Email: {c.buyer_email}"),
        ("CCCD/MSDN:", c.buyer_id),
        ("Đại diện nếu là tổ chức:", "—"),
    ]
    flowables = []
    for label, value in seller_lines:
        style = label_style if label == "BÊN BÁN:" else base_style
        flowables.append(Paragraph(f"<b>{label}</b> {value}", style))
    for label, value in buyer_lines:
        style = label_style if label == "KHÁCH HÀNG:" else base_style
        flowables.append(Paragraph(f"<b>{label}</b> {value}", style))
    return flowables


def _footer_paragraph(c: SynthContract, page_num: int, total_pages: int, footer_style) -> Paragraph:
    return Paragraph(
        f"Số: {c.contract_no} – Trang {page_num}/{total_pages}",
        footer_style,
    )


def _offer_table_flat(title: str, policy_text: str, base_style) -> Table:
    """Single 3-column table per offer section (matches original Phụ lục 01)."""
    rows = [
        [Paragraph(f"<b>{title}</b>", base_style), "", ""],
        ["TT", "Mô tả chính sách ưu đãi áp dụng", "Thành tiền (VNĐ)"],
        ["1", Paragraph(policy_text, base_style), "—"],
    ]
    t = Table(rows, colWidths=[1 * cm, 12 * cm, 4 * cm])
    t.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 1), (-1, 1), _FONT_BOLD),
                ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#d9d9d9")),
                ("SPAN", (0, 0), (-1, 0)),
                ("FONTSIZE", (0, 0), (-1, 0), 11),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return t


def render_contract_pdf(c: SynthContract, out_path: Path) -> None:
    """Render a single contract as a text-selectable PDF (3 pages)."""
    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    base, title_style, h2, label_style, footer_style = _build_styles()
    story = []

    # --- Page 1: header band + title + parties + Articles 1-3 --------
    story.append(_header_band(c, base))
    story.append(Spacer(1, 0.2 * cm))
    story.append(_title_block(c, title_style))
    story.append(Spacer(1, 0.3 * cm))
    story.append(
        Paragraph(
            f"Hợp đồng này được ký và có hiệu lực ngày {c.sign_date} giữa:",
            base,
        )
    )
    story.append(Spacer(1, 0.2 * cm))
    for flowable in _party_block(c, base, label_style):
        story.append(flowable)

    story.append(Paragraph("Điều 1. Thông tin xe và giá bán", h2))
    story.append(_vehicle_table(c, base))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(f"Số tiền bằng chữ: {c.total_price_words_vi}", base))
    story.append(
        Paragraph(
            "Giá trị Hợp đồng đã bao gồm thuế tiêu thụ đặc biệt, thuế giá trị gia tăng, "
            "nhưng không bao gồm lệ phí trước bạ, chi phí đăng ký, lưu hành, bảo hiểm xe, "
            "phí dịch vụ thuê pin và các chi phí khác.",
            base,
        )
    )

    story.append(Paragraph("Điều 2. Thanh toán", h2))
    story.append(
        Paragraph(
            f"Khách Hàng thanh toán trước {c.payment_stage_1_vnd:,} VNĐ trong vòng 03 ngày làm việc "
            f"kể từ ngày ký Hợp đồng này hoặc được chuyển thành thanh toán trước từ Thỏa thuận Đặt cọc "
            f"trước đó nhưng không muộn hơn thời hạn áp dụng của các ưu đãi.",
            base,
        )
    )
    if c.payment_method == "trả thẳng":
        story.append(
            Paragraph(
                f"Nếu trả thẳng: Khách Hàng thanh toán "
                f"{c.unit_price_vnd - c.payment_stage_1_vnd:,} VNĐ cho "
                "Bên Bán trong vòng 07 ngày làm việc kể từ ngày Bên Bán thông báo xe sẵn sàng để giao.",
                base,
            )
        )
    else:
        story.append(
            Paragraph(
                f"Nếu trả góp: Khách Hàng thanh toán vốn tự có: {c.own_capital_vnd:,} VNĐ và gửi Thông báo "
                f"tín dụng của Ngân hàng cho số tiền còn lại: {c.credit_notice_vnd:,} VNĐ, cho Bên Bán trong "
                "vòng 07 ngày làm việc kể từ ngày Bên Bán thông báo.",
                base,
            )
        )

    story.append(Paragraph("Điều 3. Giao nhận xe", h2))
    story.append(
        Paragraph(
            f"Thời gian giao nhận xe: ngày {c.delivery_date} tại {c.delivery_place}, "
            "hoặc theo thông báo của Bên Bán trước 07 ngày làm việc.",
            base,
        )
    )
    # Force a page break so the document lands at exactly 3 pages,
    # matching the VinFast template's page count.
    story.append(PageBreak())

    # --- Page 2: Articles 4, 5 + signature placeholders ---------------
    story.append(Paragraph("Điều 4. Bảo hành", h2))
    story.append(
        Paragraph(
            "Việc bảo hành được thực hiện tại các Trung tâm dịch vụ sửa chữa xe điện VinFast, "
            "theo quy định tại sổ bảo hành do Bên Bán cung cấp.",
            base,
        )
    )
    story.append(Paragraph("Điều 5. Điều khoản khác", h2))
    bullets = [
        "Xe chỉ hoạt động tốt khi được sử dụng với pin và thiết bị sạc chính hãng và được sử dụng đúng theo hướng dẫn sử dụng và sổ bảo hành được cung cấp và/hoặc đăng tải trên Website.",
        "Khách Hàng cần duy trì eSIM (nếu được tích hợp sẵn trên xe) để sử dụng các tính năng thông minh.",
        "Các thông báo của Bên Bán phải bằng văn bản, email, Ứng dụng VinFast, cuộc gọi hoặc tin nhắn.",
        "Bên Bán được chấm dứt Hợp Đồng nếu Khách Hàng vi phạm nghĩa vụ mà không khắc phục hoặc không thể khắc phục toàn bộ trong 10 ngày kể từ ngày đến hạn hoặc được thông báo.",
        "Nếu xảy ra sự kiện bất khả kháng sẽ được Các Bên xử lý theo quy định của pháp luật.",
    ]
    for b in bullets:
        story.append(Paragraph(f"- {b}", base))
    story.append(Spacer(1, 0.8 * cm))
    story.append(
        Table(
            [["KHÁCH HÀNG", "", "BÊN BÁN", ""]],
            colWidths=[5 * cm, 3 * cm, 5 * cm, 3 * cm],
            style=TableStyle(
                [
                    ("FONTNAME", (0, 0), (-1, -1), _FONT_BOLD),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ]
            ),
        )
    )
    story.append(PageBreak())

    # --- Page 3: Phụ lục 01 ------------------------------------------
    story.append(Paragraph("PHỤ LỤC 01", title_style))
    story.append(Paragraph("Các chính sách ưu đãi áp dụng", h2))

    sections = [
        ("a) Ưu đãi giảm theo Thông báo giá", c.special_offer_a),
        ("b) Ưu đãi CTKM tặng tiền", c.special_offer_b),
        ("c) Ưu đãi giảm giá cấp bậc CBNV", c.special_offer_c),
        ("d) Ưu đãi chương trình Vinclub", c.special_offer_d),
    ]
    for title, policy in sections:
        story.append(_offer_table_flat(title, policy, base))
        story.append(Spacer(1, 0.3 * cm))

    # --- Footer: page number on every page (drawn via onLaterPages) ---
    def _draw_footer(canvas_obj, doc_obj):
        canvas_obj.saveState()
        canvas_obj.setFont(_FONT_REG, 9)
        text = f"Số: {c.contract_no} – Trang {doc_obj.page}/3"
        canvas_obj.drawCentredString(
            A4[0] / 2.0,
            1.2 * cm,
            text,
        )
        canvas_obj.restoreState()

    doc.build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate synthetic VinFast-style OCR contracts."
    )
    parser.add_argument(
        "--n",
        type=int,
        default=15,
        help="Number of contracts to generate (must be in [10, 20]).",
    )
    parser.add_argument(
        "--seed-base",
        type=int,
        default=20260925,
        help="Base seed (case i uses seed_base + i).",
    )
    args = parser.parse_args()

    if not 10 <= args.n <= 20:
        raise SystemExit(f"--n must be in [10, 20] (got {args.n}).")

    contracts = [_generate_one(i + 1, args.seed_base + i) for i in range(args.n)]

    # Render PDFs
    for c in contracts:
        out_pdf = SCAN_OUT / c.source_pdf
        render_contract_pdf(c, out_pdf)

    # Write GT JSONL (one record per case, paired by case_id)
    with GT_OUT.open("w", encoding="utf-8") as f:
        for c in contracts:
            record = {
                "case_id": c.case_id,
                "source_pdf": str(Path("data/Scan") / "synth_phase03" / c.source_pdf),
                "schema_version": "phase03.synth.v1",
                "language": "vi",
                "ground_truth_fields": asdict(c),
            }
            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    # Manifest
    manifest = {
        "phase": "03-ocr-bake-off",
        "asset_kind": "synthetic-pdf-corpus",
        "n": args.n,
        "seed_base": args.seed_base,
        "schema_version": "phase03.synth.v1",
        "pdf_dir": str(SCAN_OUT.relative_to(REPO_ROOT)),
        "gt_jsonl": str(GT_OUT.relative_to(REPO_ROOT)),
        "synthetic_marker": "SYNTH- prefix on every identifier; @example.test emails.",
        "case_ids": [c.case_id for c in contracts],
    }
    MANIFEST_OUT.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    print(f"Wrote {args.n} PDFs to {SCAN_OUT}")
    print(f"Wrote GT JSONL  to {GT_OUT}")
    print(f"Wrote manifest  to {MANIFEST_OUT}")


if __name__ == "__main__":
    main()
